### ISSUE TITLE
Yet another question regarding uploads.php 

### ISSUE THREAD

**Issue by mudrd8mz** [blindsidenetworks/moodle-tinymce_recordrtc#20]
Additionally to my comments on uploads.php in the Atto variant of the plugin, I noticed that the file in both plugins is slightly different.

For example, the Atto's one does allow serving files with the component `tinymce_recordrtc` but not vice versa - TinyMCE's version does not seem to serve Atto's files.

Discrepancies like this are suspicious.

**Comment by jfederico** [comment]
Fixed after removing the custom uploads.php
