### ISSUE TITLE
Undefined indexs

### ISSUE THREAD

**Issue by gjb2048** [blindsidenetworks/moodle-tinymce_recordrtc#30]
Hello,

I'm getting (with developer debugging on) when TinyMCE is the site editor and editing the front page settings:

![Annotation 2020-01-27 210441](https://user-images.githubusercontent.com/1058419/73214158-89e31480-4149-11ea-9574-368c46ad932a.png)

Moodle 3.7.3 (Build: 20191111) with recordrtc 2019051900 1.1-beta

Thanks,

Gareth

**Comment by ffdixon** [comment]
The recordRTC is actually built into the Atto editor in the recent versions of Moodle.  What version of Moodle are you running?

**Comment by gjb2048** [comment]
Thanks for replying Fred,

As stated above 'Moodle 3.7.3 (Build: 20191111)' and using the TinyMCE editor.

Gareth

**Comment by ffdixon** [comment]
Hi Gareth,

Since Moodle merged this feature into Atto, we have put any updates to this module at a low priority.  Is it an option for you to use the Atto editor instead?

**Comment by gjb2048** [comment]
Hi Fred,

Thank you for your reply.  The charity I'm helping uses TinyMCE because of the ability to add extra menu items such as styles to the toolbar.  I'm not sure if Atto supports that in Moodle.  Hence its use.

If I were to solve this issue, would you accept the patch (after review) and update on the plugins DB?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Notes:

In TinyMCE lib.php 'get_init_params' there is:

$context = empty($options['context']) ? context_system::instance() : $options['context'];

so as $options is used at the offending line:

'contextid' => $options['context']->id,

in 'update_init_params' and yet '$context' is passed in.... so:

'contextid' => $context->id,

should be the solution.

**Comment by ffdixon** [comment]
Thanks for digging deeper -- we'll look at making this update, but for the moment this will guide others who may encounter a similar issue.

Moodle HQ as taken this code an updated/incorporated it into Atto.  I'm not personally familiar with Atto, but it looks to be very [extensible ](https://docs.moodle.org/dev/Atto#Atto_Plugins).

Thanks again for taking a closer look into this issue.

**Comment by gjb2048** [comment]
No worries Fred, just submitted a pull request with the patch.

**Comment by jfederico** [comment]
Hi Gareth,

Thanks for the PR. I have been really busy with some other projects that I have procrastinated this much on this one. I promise I will **<try to>** catch up :smile: 

Cheers

**Comment by gjb2048** [comment]
No worries Jesus, thanks for pulling the PR :).

**Comment by ffdixon** [comment]
Hi Gareth,

Our pleasure!  Do you have a twitter account?  If so, please take a moment and tweet a few good words to @bigbluebutton about your experiences with the product.  We'll RT.

**Comment by gjb2048** [comment]
Hi Fred,

I do, but not used RecordRTC much.  Will pass on to the person on the charity I'm helping though.

I miss the iMoots and BBB though :(.

Cheers,

Gareth
